-- NationVoterFile Static Data
-- This file contains statements to insert static application data into the
-- database. Run this once after creating your database
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (1, 'WA Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (2, 'Ohio Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (3, 'New York Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (4, 'Florida Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (5, 'Michigan Secretary of State', 'Secretary of State');

TRUNCATE TABLE PARTY_DIM CASCADE;
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('DEM', 'Democrat');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('REP', 'Republican');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('AI', 'American Independant');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('PF', 'Peace and Freedom');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('AMC', 'American Constitution');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('GRN', 'Green');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('LIB', 'Libretarian');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('ECO', 'Ecology');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('IDP', 'Independence Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('PSL', 'Party for socialism and Liberation');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('REF', 'Reform Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('SAP', 'Sapient');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('CON', 'Conservative');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('WOR', 'Working Families');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('WEP', 'Womens Equality');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('SCC', 'Stop Common Core');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('NLP', 'Natural Law');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('SP', 'Socialist');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('UTY', 'Unity');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('AE', 'Americans Elect');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('AMP', 'American Patriot Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('DEL', 'A Delaware Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('FED', 'Federalist Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('CIT', 'Citizen''s Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('LIB', 'Liberal Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('NEW', 'New Frontier');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('ALI', 'New Alliance');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('TAX', 'US Taxpayers');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('STS', 'National Statesman');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('UNI', 'National Unity');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('IND', 'Independent Party of Delaware');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('IPU', 'Independent Patriot Party of Utah');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('IPF', ' Independant Party of Florida');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('GPU', 'Green Party of Utah (Desert Greens)');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('PCP', 'Personal Choice Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('ROL', 'Rights of Life');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('BLU', 'Blue Enigma');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('UJP', 'Utah Justice Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('FDM', 'New York Freedom Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('RTH', 'Rent is Too Damn High ');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('TXP', ' New York Tax Payers');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('APP', ' From New York File');


INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('OTH', 'otherwise');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('UN', 'Unaffiliated');
