-- NationVoterFile Static Data
-- This file contains statements to insert static application data into the
-- database. Run this once after creating your database
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (1, 'WA Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (2, 'Ohio Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (3, 'New York Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (4, 'Florida Secretary of State', 'Secretary of State');
INSERT INTO REPORTER_DIM(REPORTER_ID, REPORTER_NAME, REPORTER_TYPE) VALUES (5, 'Michigan Secretary of State', 'Secretary of State');


INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('DEM', 'Democrat');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('REP', 'Republican');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('AI', 'American Independant');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('PF', 'Peace and Freedom');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('AMC', 'American Constitution');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('GRN', 'Green');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('LIB', 'Libretarian');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('ECO', 'Ecology');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('IDP', 'Independence Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('PSL', 'Party for socialism and Liberation');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('REF', 'Reform Party');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('SAP', 'Sapient');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('CON', 'Conservative');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('WOR', 'Working Families');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('WEP', 'Womens Equality');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('SCC', 'Stop Common Core');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('NLP', 'Natural Law');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('SP', 'Socialist');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('UTY', 'Unity');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('AE', 'Americans Elect');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('OTH', 'otherwise');
INSERT INTO PARTY_DIM(PARTY_CODE, PARTY_NAME) VALUES('UN', 'Unaffiliated');
