-- This file contains some raw DDL generated from the Oracle Data Modeller tool
-- it is not quite ready for use without some edits and tweeks. 
-- Keep the tables here until we are ready to think about them 
---

CREATE TABLE CAMPAIGN_DIM
  (
    CAMPAIGN_ID                 INTEGER NOT NULL ,
    CANDIDATE_FIRST_NAME        VARCHAR (45) ,
    CANDIDATE_LAST_NAME         VARCHAR (45) ,
    DISPLAY_NAME                VARCHAR (45) ,
    PARTY                       VARCHAR (45) ,
    FEC_CANDAIDATE_ID           VARCHAR (45) ,
    POSITION                    VARCHAR (45) ,
    CAMPAIGN_PRINCIPAL_COMMTTEE VARCHAR (45) ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    CAMPAIGN_PRINCIPAL_COMMITTEE_FEC_ID VARCHAR (45) ,
    WEBSITE                             VARCHAR (45) ,
    FACEBOOK_PAGE                       VARCHAR (45) ,
    TWITTTER_USER                       VARCHAR (45)
  ) ;
ALTER TABLE CAMPAIGN_DIM ADD CONSTRAINT CAMPAIGN_DIM_PK PRIMARY KEY ( CAMPAIGN_ID ) ;


CREATE TABLE CANVASSING_CHANNEL_DIM
  (
    CANVASSING_CHANNEL_ID INTEGER NOT NULL ,
    CHANNEL               VARCHAR (45)
  ) ;
ALTER TABLE CANVASSING_CHANNEL_DIM ADD CONSTRAINT CANVASSING_CHANNEL_DIM_PK PRIMARY KEY ( CANVASSING_CHANNEL_ID ) ;


CREATE TABLE CANVASSING_FACT
  (
    CANVASSING_ID           INTEGER NOT NULL ,
    CONTACT_DATE            DATE ,
    CANDIDATE_SUPPORTED     VARCHAR (45) ,
    CANDDIATE_SUPPORT_LEVEL VARCHAR (45) ,
    VOLUNTEER_OK            VARCHAR (45) ,
    TOP_ISSUE               VARCHAR (45) ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    CANVASSING_CHANNEL_DIM_CANVASSING_CHANNEL_ID INTEGER NOT NULL ,
    HOUSEHOLD_DIM_HOUSEHOLD_ID                   INTEGER NOT NULL ,
    CAMPAIGN_DIM_CAMPAIGN_ID                     INTEGER NOT NULL ,
    REPORTER_DIM_REPORTER_ID                         INTEGER NOT NULL ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    STATE_HOUSE_DISTRICT_DIM_STATE_HOUSE_DISTRICT_ID INTEGER NOT NULL ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    STATE_SENATE_DISTRICT_DIM_STATE_SENATE_DISTRICT_ID INTEGER NOT NULL ,
    WARD_DIM_WARD_ID                                   INTEGER NOT NULL ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    CONGRESSIONAL_DISTRICT_DIM_CONGRESSIONAL_DISTRICT_ID INTEGER NOT NULL ,
    DATE_DIM_DATE_ID                                     INTEGER NOT NULL ,
    VOTER_DIM_VOTER_ID                                   INTEGER NOT NULL ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    SOCIAL_MEDIA_ACCOUNT_DIM_SOCIAL_MEDIA_ACCOUNT_ID INTEGER NOT NULL ,
    COMMITEE_DIM_COMMITEE_ID                         INTEGER NOT NULL
  ) ;
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_PK PRIMARY KEY ( CANVASSING_ID, WARD_DIM_WARD_ID ) ;


CREATE TABLE COMMITEE_DIM
  (
    COMMITEE_ID      INTEGER NOT NULL ,
    NAME             VARCHAR (45) ,
    COMMITTEE_TYPE   VARCHAR (45) ,
    PARTY            VARCHAR (45) ,
    FEC_REFERENCE_ID VARCHAR (45)
  ) ;
ALTER TABLE COMMITEE_DIM ADD CONSTRAINT COMMITEE_DIM_PK PRIMARY KEY ( COMMITEE_ID ) ;


CREATE TABLE CONGRESSIONAL_DISTRICT_DIM
  (
    CONGRESSIONAL_DISTRICT_ID INTEGER NOT NULL ,
    DISTRICT_NAME             VARCHAR (45) ,
    STATE                     VARCHAR (45) ,
    DISTRICT_NUMBER           VARCHAR (45) ,
    VALID_FROM                DATE ,
    VALID_TO                  DATE ,
    GEOMETRY                  VARCHAR (45)
  ) ;
ALTER TABLE CONGRESSIONAL_DISTRICT_DIM ADD CONSTRAINT CONGRESSIONAL_DISTRICT_DIM_PK PRIMARY KEY ( CONGRESSIONAL_DISTRICT_ID ) ;


CREATE TABLE CONTRIBUTION_FACT
  (
    CONTRIBUTION_ID          INTEGER NOT NULL ,
    AMOUNT                   VARCHAR (45) ,
    CONTRIBUTION_DATE        DATE ,
    REPORTER_DIM_REPORTER_ID     INTEGER NOT NULL ,
    COMMITEE_DIM_COMMITEE_ID INTEGER NOT NULL ,
    CAMPAIGN_DIM_CAMPAIGN_ID INTEGER NOT NULL ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    CONGRESSIONAL_DISTRICT_DIM_CONGRESSIONAL_DISTRICT_ID INTEGER NOT NULL ,
    DATE_DIM_DATE_ID                                     INTEGER NOT NULL ,
    VOTER_DIM_VOTER_ID                                   INTEGER NOT NULL ,
    WARD_DIM_WARD_ID                                     INTEGER NOT NULL ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    STATE_HOUSE_DISTRICT_DIM_STATE_HOUSE_DISTRICT_ID INTEGER NOT NULL ,
    --  ERROR: COLUMN NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
    STATE_SENATE_DISTRICT_DIM_STATE_SENATE_DISTRICT_ID INTEGER NOT NULL
  ) ;
ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_PK PRIMARY KEY ( CONTRIBUTION_ID ) ;


CREATE TABLE COUNTY_DIM
  (
    COUNTRY_ID   INTEGER NOT NULL ,
    STATE_NAME   VARCHAR (45) ,
    STATE_ABBREV VARCHAR (45) ,
    COUNTY_NAME  VARCHAR (45) ,
    GEOMETRY     VARCHAR (45)
  ) ;
ALTER TABLE COUNTY_DIM ADD CONSTRAINT COUNTY_DIM_PK PRIMARY KEY ( COUNTRY_ID ) ;


CREATE TABLE COUNTY_DISTRICT_DIM
  (
    COUNTY_DISTRICT_ID INTEGER NOT NULL ,
    STATE              VARCHAR (45) ,
    COUNTY             VARCHAR (45) ,
    DISTRICT_NAME      VARCHAR (45) ,
    GEOMETRY MDSYS.SDO_GEOMETRY ,
    COUNTY_DISTRICT_ID1 INTEGER NOT NULL
  ) ;
ALTER TABLE COUNTY_DISTRICT_DIM ADD CONSTRAINT COUNTY_DISTRICT_DIM_PK PRIMARY KEY ( COUNTY_DISTRICT_ID ) ;









CREATE TABLE SOCIAL_MEDIA_ACCOUNT_DIM
  (
    SOCIAL_MEDIA_ACCOUNT_ID INTEGER NOT NULL ,
    FACEBOOK_ACCOUNT        VARCHAR (45) ,
    TWITTER_ACCOUNT         VARCHAR (45) ,
    LINKED_IN_ACCOUNT       VARCHAR (45) ,
    PERSON_DIM_PERSON_ID    INTEGER NOT NULL
  ) ;
CREATE UNIQUE INDEX SOCIAL_MEDIA_ACCOUNT_DIM__IDX ON SOCIAL_MEDIA_ACCOUNT_DIM
  (
    PERSON_DIM_PERSON_ID ASC
  )
  LOGGING ;
ALTER TABLE SOCIAL_MEDIA_ACCOUNT_DIM ADD CONSTRAINT SOCIAL_MEDIA_ACCOUNT_DIM_PK PRIMARY KEY ( SOCIAL_MEDIA_ACCOUNT_ID ) ;


CREATE TABLE STATE_DIM
  (
    STATE_ID     INTEGER NOT NULL ,
    STATE_NAME   VARCHAR (45) ,
    STATE_ABBREV VARCHAR (45) ,
    GEOMETRY     VARCHAR (45)
  ) ;
ALTER TABLE STATE_DIM ADD CONSTRAINT STATE_DIM_PK PRIMARY KEY ( STATE_ID ) ;


CREATE TABLE STATE_HOUSE_DISTRICT_DIM
  (
    STATE_HOUSE_DISTRICT_ID INTEGER NOT NULL ,
    STATE                   VARCHAR (45) ,
    DISTRICT_NAME           VARCHAR (45) ,
    GEOMETRY                VARCHAR (45)
  ) ;
ALTER TABLE STATE_HOUSE_DISTRICT_DIM ADD CONSTRAINT STATE_HOUSE_DISTRICT_DIM_PK PRIMARY KEY ( STATE_HOUSE_DISTRICT_ID ) ;


CREATE TABLE STATE_SENATE_DISTRICT_DIM
  (
    STATE_SENATE_DISTRICT_ID INTEGER NOT NULL ,
    STATE                    VARCHAR (45) ,
    DISTRICT_NAME            VARCHAR (45) ,
    GEOMETRY                 VARCHAR (45)
  ) ;
ALTER TABLE STATE_SENATE_DISTRICT_DIM ADD CONSTRAINT STATE_SENATE_DISTRICT_DIM_PK PRIMARY KEY ( STATE_SENATE_DISTRICT_ID ) ;




CREATE TABLE WARD_DIM
  (
    WARD_ID    INTEGER NOT NULL ,
    STATE      VARCHAR (45) ,
    COUNTY     VARCHAR (45) ,
    CITY       VARCHAR (45) ,
    WARD_NAME  VARCHAR (45) ,
    WARD_NAME1 VARCHAR (45)
  ) ;
ALTER TABLE WARD_DIM ADD CONSTRAINT WARD_DIM_PK PRIMARY KEY ( WARD_ID ) ;


--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_CAMPAIGN_DIM_FK FOREIGN KEY ( CAMPAIGN_DIM_CAMPAIGN_ID ) REFERENCES CAMPAIGN_DIM ( CAMPAIGN_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_CANVASSING_CHANNEL_DIM_FK FOREIGN KEY ( CANVASSING_CHANNEL_DIM_CANVASSING_CHANNEL_ID ) REFERENCES CANVASSING_CHANNEL_DIM ( CANVASSING_CHANNEL_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_COMMITEE_DIM_FK FOREIGN KEY ( COMMITEE_DIM_COMMITEE_ID ) REFERENCES COMMITEE_DIM ( COMMITEE_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_CONGRESSIONAL_DISTRICT_DIM_FK FOREIGN KEY ( CONGRESSIONAL_DISTRICT_DIM_CONGRESSIONAL_DISTRICT_ID ) REFERENCES CONGRESSIONAL_DISTRICT_DIM ( CONGRESSIONAL_DISTRICT_ID ) NOT DEFERRABLE ;

ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_DATE_DIM_FK FOREIGN KEY ( DATE_DIM_DATE_ID ) REFERENCES DATE_DIM ( DATE_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_HOUSEHOLD_DIM_FK FOREIGN KEY ( HOUSEHOLD_DIM_HOUSEHOLD_ID ) REFERENCES HOUSEHOLD_DIM ( HOUSEHOLD_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_REPORTER_DIM_FK FOREIGN KEY ( REPORTER_DIM_REPORTER_ID ) REFERENCES REPORTER_DIM ( REPORTER_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_SOCIAL_MEDIA_ACCOUNT_DIM_FK FOREIGN KEY ( SOCIAL_MEDIA_ACCOUNT_DIM_SOCIAL_MEDIA_ACCOUNT_ID ) REFERENCES SOCIAL_MEDIA_ACCOUNT_DIM ( SOCIAL_MEDIA_ACCOUNT_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_STATE_HOUSE_DISTRICT_DIM_FK FOREIGN KEY ( STATE_HOUSE_DISTRICT_DIM_STATE_HOUSE_DISTRICT_ID ) REFERENCES STATE_HOUSE_DISTRICT_DIM ( STATE_HOUSE_DISTRICT_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_STATE_SENATE_DISTRICT_DIM_FK FOREIGN KEY ( STATE_SENATE_DISTRICT_DIM_STATE_SENATE_DISTRICT_ID ) REFERENCES STATE_SENATE_DISTRICT_DIM ( STATE_SENATE_DISTRICT_ID ) NOT DEFERRABLE ;

ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_VOTER_DIM_FK FOREIGN KEY ( VOTER_DIM_VOTER_ID ) REFERENCES VOTER_DIM ( VOTER_ID ) NOT DEFERRABLE ;

ALTER TABLE CANVASSING_FACT ADD CONSTRAINT CANVASSING_FACT_WARD_DIM_FK FOREIGN KEY ( WARD_DIM_WARD_ID ) REFERENCES WARD_DIM ( WARD_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_CAMPAIGN_DIM_FK FOREIGN KEY ( CAMPAIGN_DIM_CAMPAIGN_ID ) REFERENCES CAMPAIGN_DIM ( CAMPAIGN_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_COMMITEE_DIM_FK FOREIGN KEY ( COMMITEE_DIM_COMMITEE_ID ) REFERENCES COMMITEE_DIM ( COMMITEE_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_CONGRESSIONAL_DISTRICT_DIM_FK FOREIGN KEY ( CONGRESSIONAL_DISTRICT_DIM_CONGRESSIONAL_DISTRICT_ID ) REFERENCES CONGRESSIONAL_DISTRICT_DIM ( CONGRESSIONAL_DISTRICT_ID ) NOT DEFERRABLE ;

ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_DATE_DIM_FK FOREIGN KEY ( DATE_DIM_DATE_ID ) REFERENCES DATE_DIM ( DATE_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_REPORTER_DIM_FK FOREIGN KEY ( REPORTER_DIM_REPORTER_ID ) REFERENCES REPORTER_DIM ( REPORTER_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_STATE_HOUSE_DISTRICT_DIM_FK FOREIGN KEY ( STATE_HOUSE_DISTRICT_DIM_STATE_HOUSE_DISTRICT_ID ) REFERENCES STATE_HOUSE_DISTRICT_DIM ( STATE_HOUSE_DISTRICT_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_STATE_SENATE_DISTRICT_DIM_FK FOREIGN KEY ( STATE_SENATE_DISTRICT_DIM_STATE_SENATE_DISTRICT_ID ) REFERENCES STATE_SENATE_DISTRICT_DIM ( STATE_SENATE_DISTRICT_ID ) NOT DEFERRABLE ;

ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_VOTER_DIM_FK FOREIGN KEY ( VOTER_DIM_VOTER_ID ) REFERENCES VOTER_DIM ( VOTER_ID ) NOT DEFERRABLE ;

ALTER TABLE CONTRIBUTION_FACT ADD CONSTRAINT CONTRIBUTION_FACT_WARD_DIM_FK FOREIGN KEY ( WARD_DIM_WARD_ID ) REFERENCES WARD_DIM ( WARD_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE SOCIAL_MEDIA_ACCOUNT_DIM ADD CONSTRAINT SOCIAL_MEDIA_ACCOUNT_DIM_PERSON_DIM_FK FOREIGN KEY ( PERSON_DIM_PERSON_ID ) REFERENCES PERSON_DIM ( PERSON_ID ) NOT DEFERRABLE ;

ALTER TABLE VOTER_DIM ADD CONSTRAINT VOTER_DIM_PERSON_DIM_FK FOREIGN KEY ( PERSON_DIM_PERSON_ID ) REFERENCES PERSON_DIM ( PERSON_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_STAFFER_DIM_FK FOREIGN KEY ( STAFFER_DIM_STAFFER_ID ) REFERENCES STAFFER_DIM ( STAFFER_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_CAMPAIGN_DIM_FK FOREIGN KEY ( CAMPAIGN_DIM_CAMPAIGN_ID ) REFERENCES CAMPAIGN_DIM ( CAMPAIGN_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_CONGRESSIONAL_DISTRICT_DIM_FK FOREIGN KEY ( CONGRESSIONAL_DISTRICT_DIM_CONGRESSIONAL_DISTRICT_ID ) REFERENCES CONGRESSIONAL_DISTRICT_DIM ( CONGRESSIONAL_DISTRICT_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_COUNTY_DIM_FK FOREIGN KEY ( COUNTRY_KEY ) REFERENCES COUNTY_DIM ( COUNTRY_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_COUNTY_DIM_FKV1 FOREIGN KEY ( COUNTY_DIM_COUNTRY_ID ) REFERENCES COUNTY_DIM ( COUNTRY_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_COUNTY_DISTRICT_DIM_FK FOREIGN KEY ( COUNTY_DISTRICT_DIM_COUNTY_DISTRICT_ID ) REFERENCES COUNTY_DISTRICT_DIM ( COUNTY_DISTRICT_ID ) NOT DEFERRABLE ;

ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_DATE_DIM_FK FOREIGN KEY ( DATE_DIM_DATE_ID ) REFERENCES DATE_DIM ( DATE_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_HOUSEHOLD_DIM_FK FOREIGN KEY ( HOUSEHOLD_DIM_HOUSEHOLD_ID ) REFERENCES HOUSEHOLD_DIM ( HOUSEHOLD_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_REPORTER_DIM_FK FOREIGN KEY ( REPORTER_KEY ) REFERENCES REPORTER_DIM ( REPORTER_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_REPORTER_DIM_FKV1 FOREIGN KEY ( REPORTER_DIM_REPORTER_ID ) REFERENCES REPORTER_DIM ( REPORTER_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_SOCIAL_MEDIA_ACCOUNT_DIM_FK FOREIGN KEY ( SOCIAL_MEDIA_ACCOUNT_DIM_SOCIAL_MEDIA_ACCOUNT_ID ) REFERENCES SOCIAL_MEDIA_ACCOUNT_DIM ( SOCIAL_MEDIA_ACCOUNT_ID ) NOT DEFERRABLE ;

ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_STATE_DIM_FK FOREIGN KEY ( STATE_DIM_STATE_ID ) REFERENCES STATE_DIM ( STATE_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_STATE_HOUSE_DISTRICT_DIM_FK FOREIGN KEY ( STATE_HOUSE_DISTRICT_DIM_STATE_HOUSE_DISTRICT_ID ) REFERENCES STATE_HOUSE_DISTRICT_DIM ( STATE_HOUSE_DISTRICT_ID ) NOT DEFERRABLE ;

--  ERROR: FK NAME LENGTH EXCEEDS MAXIMUM ALLOWED LENGTH(30)
ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_STATE_SENATE_DISTRICT_DIM_FK FOREIGN KEY ( STATE_SENATE_DISTRICT_DIM_STATE_SENATE_DISTRICT_ID ) REFERENCES STATE_SENATE_DISTRICT_DIM ( STATE_SENATE_DISTRICT_ID ) NOT DEFERRABLE ;

ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_VOTER_DIM_FK FOREIGN KEY ( VOTER_DIM_VOTER_ID ) REFERENCES VOTER_DIM ( VOTER_ID ) NOT DEFERRABLE ;

ALTER TABLE VOTER_REPORT_FACT ADD CONSTRAINT VOTER_REPORT_FACT_WARD_DIM_FK FOREIGN KEY ( WARD_DIM_WARD_ID ) REFERENCES WARD_DIM ( WARD_ID ) NOT DEFERRABLE ;

--  ERROR: INVALID DIMENSION WITHOUT LEVELS: VOTER_DIM

CREATE SEQUENCE HOUSEHOLD_DIM_HOUSEHOLD_ID_SEQ START WITH 1 NOCACHE ORDER ;
CREATE OR REPLACE TRIGGER HOUSEHOLD_DIM_HOUSEHOLD_ID_TRG BEFORE
  INSERT ON HOUSEHOLD_DIM FOR EACH ROW WHEN (NEW.HOUSEHOLD_ID IS NULL) BEGIN :NEW.HOUSEHOLD_ID := HOUSEHOLD_DIM_HOUSEHOLD_ID_SEQ.NEXTVAL;
END;
/


-- ORACLE SQL DEVELOPER DATA MODELER SUMMARY REPORT: 
-- 
-- CREATE TABLE                            20
-- CREATE INDEX                             1
-- ALTER TABLE                             59
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           1
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          1
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                  44
-- WARNINGS                                 0
